version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/axcdnt/ecs-explorer
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: "Release ecs-explorer"
          command: |
            export GITHUB_TOKEN=$GITHUB_TOKEN
            curl -sL https://git.io/goreleaser | bash

workflows:
  main:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/